<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title> Viaspace : Giant King Grass Pellets </title>
<?php include_once('inc_meta.php'); ?>
</head>

 <body>
 <div id="main_container" class="main_container">
	
					<?php include_once('inc_header.php'); ?>

				<?php include_once('inc_menu2.php'); ?>

				<div id="body" class="body">
					<div id="lmenu" class="lmenu">
						<div id="list-menu" class="list-menu">
							<ul>								
								<li><a href="index.php">Home</a></li>
								<li class="header">Green Applications</li>
								<li><a href="green_electricity.php">> Green Electricty</a></li>
								<li class="currentlink">> Giant King Grass Pellets</li>
								
								<li><a href="biochemicals_bio_plastics.php">> Biofuels & Biochemicals</a></li>
								<li><a href="bio_methane.php">> Biomethane</a></li>
							</ul>
						</div>
					</div>
					<div id="body_content" class="body_content">
					
					<h1>Giant King<sup>&reg</sup> Grass Pellets & Biocoal to Replace Coal in Existing Power Plants</h1><hr />
					<br/><br/>
					Over 40% of electricity worldwide is generated by coal-fired power plants. Coal has the largest carbon dioxide emissions per unit energy of all fossil fuels, and coal-fired power plants are a major source of man-made carbon dioxide emissions. Coal-fired power plants generally have a life of 20 to 50 years and represent a huge global capital investment. It is not economically feasible to retire these coal-fired power plants and replace them with greener technology. It is possible, however, to reduce their carbon dioxide emissions by replacing some of the coal with biomass - burning both fuels together which is called co-firing. 
					<br/><br/>

					Several European countries and Japan and Korea have mandated carbon dioxide emissions reductions from their power plants and have provided incentives, subsidies and feed in tariffs that make co-firing of biomass with coal financially feasible. Biomass pellets are considerably more expensive than coal and would not be an attractive option on price alone.
					<br/><br/>

					An older and larger market for pellets is for residential and business heating in winter. Some countries have district heating where the heat is generated in a central location and distributed in the form of hot water or steam. Combined heat and power (CHP) systems generate both heat and electricity. There are also residential heating systems designed for pellets and these can be domestic boilers that generate hot water, or simple pellet stoves.
					<br/><br/>
					The vast majority of pellets produced and consumed in the world are made from wood.
					<br/><br/>
					<div class="figure">
					  <img src="images/pellets/woodpelletproduction.jpg" width="600px" alt="Global wood pellet consumption. About 60% of the pellets are used for heating, and 40% for industrial uses mostly electricity generation.">
					  <p>Global wood pellet consumption. About 60% of the pellets are used for heating, and 40% for industrial uses mostly electricity generation.</p>
					</div>
					<br/><br/>
					<br/><br/>
					For comparison, 2015 the worldwide coal production was about 7500 million metric tons-- 278 times larger than the global biomass pellet reduction.  Europe is the largest producer of biomass pellets, and also the largest consumer. The demand for pellets in Europe is larger than supply, and Europe is the largest importer of pellets. The United States is the second largest producer of pellets and Canada is third. To assure a supply of biomass for their power plants, several European utilities have set up pellet mills in the US near the source of sawdust and other waste wood.
					Japan and Korea are importing wood pellets, and China is both producing and using pellets.
					<br/>
					<h2>Giant King Grass Pellets</h2>
					Giant King Grass has been made into pellets which have been tested by several independent laboratories. Pictures of Giant King Grass pellets and a typical analysis are shown below.
					<div class="figure">
					<table width="600px" id="pellets">
						<tr>
							<td style="width:200px">
								<img src="images/pellets/pellets1.jpg" width="232px" height="259px"/>
							</td>
							<td style="width:380px">
								<img src="images/pellets/pellets2.jpg" width="368px" height="259px" />
							</td>
						</tr>
					</table>
					<p>
						Giant King Grass pellets have the same size and shape as wood pellets.
					</p>
					</div>
					<br/>
					<div class="figure">
					<table width="600px" id="biomass-analysis">
						<tr>
							<td style="width:463px">
								<img src="images/pellets/analysis.jpg"  />
							</td>
							<td style="width:100px">
								<img src="images/pellets/bel-logo.jpg" width="137px" />
							</td>
						</tr>
					</table>
					<p>
						Analysis of Giant King Grass pellets by Biomass Energy Lab
					</p>
					</div>
					<br/>
					Note that a local Giant King Grass power plant does not need to make pellets.  Chopped and dried Giant King Grass can be used directly which avoids the cost of making pellets. Pellets are only needed if the biomass must be shipped over long distances.
					<br/>
					<br/><br/>
					<h2>Biocoal</h2>
					The use of biomass pellets is well established, but has some limitations. Traditional biomass pellets have lower energy density per ton compared to coal, and they cannot be stored outdoors in the rain because they absorb moisture and disintegrate. New processes including torrefaction and hydrothermal catalysis convert biomass into biocoal which is pelletized and has properties very similar to ordinary coal.  It has the same energy density and can be stored outdoors. Biocoal can be mixed in any proportion with coal and pulverized in the same machines. Biocoal burns cleanly and does produce the mercury or sulfur emissions of coal. Giant King Grass has been converted into biocoal and has the same energy density as good metallurgical quality coal.
					<br/><br/>
				</div>				
				<br/><br/>
			</div>
			<br/><br/>
			<?php include_once('inc_footer.php'); ?>
