<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title> Viaspace : Giant King Grass Pellets </title>
<?php include_once('inc_meta.php'); ?>
</head>

 <body>
 <div id="main_container" class="main_container">
	
					<?php include_once('inc_header.php'); ?>

				<?php include_once('inc_menu2.php'); ?>

				<div id="body" class="body">
					<div id="lmenu" class="lmenu">
						<div id="list-menu" class="list-menu">
							<ul>								
								<li><a href="index.php">Home</a></li>
								<li class="header">Green Applications</li>
								<li><a href="green_electricity.php">> Green Electricty</a></li>
								<li class="currentlink">> Giant King Grass Pellets</li>
								
								<li><a href="biochemicals_bio_plastics.php">> Biofuels & Biochemicals</a></li>
								<li><a href="bio_methane.php">> Bio-Methane</a></li>
							</ul>
						</div>
					</div>
					<div id="body_content" class="body_content">
					
					<h1>Giant King<sup>&trade;</sup> Grass Pellets for Coal Replacement</h1><hr />
					
					<b>Co-firing Giant King Grass pellets with coal in existing power plants represents an extremely large green energy market for Giant King Grass.</b><br /><br />
					
					Over 40% of electricity worldwide is generated by coal-fired power plants. Coal has the largest carbon dioxide emissions per unit energy of all fossil fuels, and coal-fired power plants are a major source of man-made carbon dioxide emissions. Coal-fired power plants generally have a life of 20 to 50 years and represent a huge global capital investment. It is not economically feasible to retire these coal-fired power plants and replace them with greener technology. It is possible, however, to reduce their carbon dioxide emissions by replacing some of the coal with biomass - burning both fuels together which is called co-firing.<br /><br />

					<b>A straightforward and modest cost modification can allow most coal-fired power plants to replace up to 20% of the coal currently being used with biomass pellets, and thus reduce the power plant's carbon dioxide emissions by 20%. Co-firing will allow power plants to meet their carbon emissions reductions targets for the next decade. Many coal-fired power plants in Europe have been co-firing for more than 10 years.</b><br /><br />

					<img src="images/biomass_pellets_lifecycle.png" alt="" /><br /><br />
					
					The reason for the limitation to 20% for co-firing is that the boilers in the coal power plant are generally not compatible with larger amounts of biomass. New power plants with different boiler technology that use 100% biomass are now widely available and receiving a lot of attention due to their green technology.

					Torrefaction is an emerging technology that converts biomass into bio coal that can be directly substituted in any amount for coal in existing coal-fired power plants. Bio coal has high energy density and can be stored outdoors just like coal.<br /><br />
					
					<h2>Biomass Pellets-Overview</h2>					
					Biomass is inherently bulky and difficult to transport and store -- think of a bale of hay. Shipping bales of hay from a plantation in Asia or Africa to a customer in Europe or the US is not practical. The volume of the biomass must be reduced in a process called densification, and pellets are a good example. A pellet is simply biomass that is dried, made into a powder and pressed under high pressure into a pellet that is about the thickness of a pencil and 1 inch long. For large-scale applications, pellets are shipped in bulk in the hold of a ship, and handling is similar to the handling of bulk rice or grain.<br /><br />

					<table>
						<tr>
							<td><img src="images/gkc_pellets_coins.jpg" width="217" alt="" /></td>
							<td><img src="images/gkg_pellets.jpg" width="380" alt="" /></td>
						</tr>
					</table>&nbsp;&nbsp;<i>Giant King Grass Pellets</i><br /><br />

					<h2>Properties of Biomass Pellets</h2>
										
					Pellets have several advantages compared to their raw biomass feedstock. The pellets are more energy dense and easier to transport and feed into automated feed systems. These advantages, when combined with the renewable and environmentally sound properties of the feedstock, make biomass pellets a viable source of green energy.<br /><br />

					A wide array of biomass materials can be used to manufacture pellets. Most pellets today are made from sawdust and other wood waste. The demand for pellets has exceeded the amount of wood and agricultural waste available, and dedicated energy crops such as Giant King Grass are strong alternatives. Pellet mills are commercial enterprises, and equipment for making pellets is available from many sources.<br /><br />

					A biomass briquette is similar to a pellet but is larger-- up to 3 1/2 inches in diameter and 1 foot long. Briquettes are often used in industrial applications that generate heat or steam rather than electricity.<br /><br />

					<table>
						<tr>
							<td><img src="images/pellets_analysis.png" width="463" height="154" alt="" /></td>
							<td><img src="images/pellets_BEL.png" width="125" alt="" /></td>
						</tr>
					</table><br /><br />

				</div>				
			</div>
			<?php include_once('inc_footer.php'); ?>